import * as Joi from 'joi';

export default Joi.object({
	NODE_ENV: Joi.string()
		.valid('development', 'production', 'test', 'provision')
		.default('development'),
	VCF_IOBIO_HOST: Joi.string().required(),
	ALLOWED_ORIGINS: Joi.string().default('http://localhost:4200'),
	IGV_HOST: Joi.string().required().default(''),
	VEP_TOKEN: Joi.string().required(),
	FASTQ_TOKEN: Joi.string().required(),
	DB_PORT: Joi.number().port().default(3306),
	DB_PASSWORD: Joi.string().required(),
	DB_HOST: Joi.string().required(),
	DB_DATABASE: Joi.string().required(),
	DB_USERNAME: Joi.string().required(),
	MONGO_DB_PREFIX: Joi.string().required(),
	MONGO_DB_HOST: Joi.string().required(),
	MONGO_DB_PORT: Joi.number().port().default(28000).required(),
	MONGO_DB_DATABASE: Joi.string().required(),
	MONGO_IMPORT_CMD: Joi.string().required(),
	MONGO_MOUNT_FOLDER: Joi.string().required(),
	MONGO_CHAT_COLLECTION: Joi.string().required(),
	JWT_SECRET: Joi.string().required(),
	JWT_ACCESS_TOKEN_EXPIRED: Joi.string().required(),
	MAIL_USER: Joi.string().required(),
	MAIL_PASSWORD: Joi.string().required(),
	MAIL_HOST: Joi.string().required(),
	AWS_ACCESS_KEY: Joi.string().required(),
	AWS_SECRET_KEY: Joi.string().required(),
	AWS_BUCKET: Joi.string().required(),
	AWS_REGION: Joi.string().required(),
	OPENAI_API_KEY: Joi.string().required(),
	OPENAI_MODEL: Joi.string().required(),
	GENEBE_USERNAME: Joi.string().required(),
	GENEBE_API_KEY: Joi.string().required(),
	MOUNT_FOLDER: Joi.string().required(),
	EXPORT_FOLDER: Joi.string().required(),
	ANALYSIS_FOLDER: Joi.string().required(),
	UPLOAD_FOLDER: Joi.string().required(),
	FASTA_FOLDER: Joi.string().required(),
	PAYOS_CLIENT_ID: Joi.string().required(),
	PAYOS_API_KEY: Joi.string().required(),
	PAYOS_CHECKSUM_KEY: Joi.string().required(),
	REDIS_HOST: Joi.string().required(),
	REDIS_PORT: Joi.number().port().default(6379).required(),
});
